"""AAA-81 Sub-step 2 — diverse page_type mini-sweep.

5 URLs × 3 independent classify_multi_dim calls = 15 measurements.

Discovery-only path (NOT full audit() — skips fan-out, ChatGPT, AI Overview,
keyword volume, etc., per spec). Bypass methodology proven in AAA-110 S0:
- ONE crawl + site_profile + keyword extraction per URL (shared inputs).
- THREE independent classify_multi_dim calls per URL (the measurement).
Inputs are constant within a URL; output variance is the classifier's only.

For URL #1 (aboutyou product) and #5 (telex article) — resolve concrete
URLs upfront by crawling discovery pages and extracting links.
"""
import asyncio
import json
import os
import re
import time
from urllib.parse import urljoin

# AAA-62 — gemini-3-flash-preview only exists in 'global' location. The
# Discovery/RE agents hard-set this at import time; standalone probes must
# replicate. Without this, the multi_dim_classify Gemini call 404s silently.
os.environ.setdefault("GOOGLE_GENAI_USE_VERTEXAI", "True")
os.environ["GOOGLE_CLOUD_LOCATION"] = "global"

from crawler.crawler import crawl_html
from site_profile.profile import analyze_site_profile
from page_analysis.keywords import extract_target_keywords
from page_analysis.multi_dim_classify import classify_multi_dim
from site_profile.gemini_analyzer import get_usage


URL_ANCHORS = {
    "aboutyou_product_discovery": "https://www.aboutyou.hu/c/noi",
    "telex_article_discovery": "https://telex.hu/",
}

# Fixed URLs (from spec):
FIXED = {
    "aboutyou_category": "https://www.aboutyou.hu/c/noi",
    "vercel_pricing": "https://vercel.com/pricing",
    "nextjs_docs": "https://nextjs.org/docs",
}


def _extract_product_url(html: str) -> str | None:
    """aboutyou.hu product URLs look like /p/<brand>/<slug>-<id> ."""
    matches = re.findall(r'href="(/p/[^"]+)"', html or "")
    for m in matches:
        # avoid placeholders / paginated junk
        if m.endswith(".") or "?" in m:
            continue
        return urljoin("https://www.aboutyou.hu", m)
    return None


def _extract_article_url(html: str, host_prefix: str) -> str | None:
    """telex.hu articles are at /<section>/YYYY/MM/DD/<slug>."""
    # link with full path, 4-digit year, looks like an article
    matches = re.findall(r'href="([^"]+)"', html or "")
    for m in matches:
        if not m: continue
        full = m if m.startswith("http") else urljoin(host_prefix, m)
        if "telex.hu" not in full: continue
        # date-style path
        if re.search(r"/\d{4}/\d{2}/\d{2}/", full):
            return full
    return None


async def resolve_dynamic_urls() -> dict:
    out = {}
    print("Pre-flight: resolving dynamic URLs...", flush=True)

    # aboutyou product — crawl /c/noi and pull first /p/ link
    cr = await crawl_html(URL_ANCHORS["aboutyou_product_discovery"])
    raw = cr.get("_raw_html_transient") or ""
    if not raw:
        # fall back to a known content field
        raw = (cr.get("content") or {}).get("visible_text") or ""
    product = _extract_product_url(raw)
    out["aboutyou_product"] = product
    print(f"  aboutyou product : {product}", flush=True)

    cr2 = await crawl_html(URL_ANCHORS["telex_article_discovery"])
    raw2 = cr2.get("_raw_html_transient") or ""
    article = _extract_article_url(raw2, "https://telex.hu")
    out["telex_article"] = article
    print(f"  telex article    : {article}", flush=True)

    return out


async def probe_one_url(url: str, expected_pt: str, expected_intent: str) -> dict:
    """1 crawl + 1 profile + 1 keywords + 3 classify calls."""
    setup_cost_before = get_usage().get("cost", 0.0)
    t0 = time.perf_counter()

    try:
        crawl = await crawl_html(url)
        sp = await analyze_site_profile(crawl)
        kw = await extract_target_keywords(crawl, sp)
    except Exception as e:
        return {"url": url, "expected_pt": expected_pt, "error_setup": f"{type(e).__name__}: {e}"}

    setup_cost = round(get_usage().get("cost", 0.0) - setup_cost_before, 6)

    # Build a minimal summary from the available signals (the full summary
    # is generated by the ADK Discovery agent's final synthesis step,
    # which we skip per Sub-step 2 spec). Classifier inputs primarily for
    # page_type are URL/title/h1/schema/main_content excerpt anyway.
    summary = (
        f"Page on {sp.get('brand', '?')} ({sp.get('language')}/"
        f"{sp.get('location')}). Topic cluster: {kw.get('topic_cluster')}. "
        f"Primary keyword: {kw.get('primary_keyword')}. Category keyword: "
        f"{kw.get('category_keyword')}. {kw.get('reasoning') or ''}"
    )

    runs = []
    for r in range(1, 4):
        cb = get_usage().get("cost", 0.0)
        md, md_cost = await classify_multi_dim(crawl, sp, summary)
        runs.append({
            "run": r,
            "page_type": md.get("page_type"),
            "parent_intent_group": md.get("page_type_parent_intent_group"),
            "business_model": md.get("business_model"),
            "topic_domain": md.get("topic_domain"),
            "locality": md.get("locality"),
            "audience_primary": md.get("audience_relationship_primary"),
            "audience_secondary": md.get("audience_relationship_secondary"),
            "audience_confidence": md.get("audience_confidence"),
            "classify_cost": md_cost,
            "_error": md.get("_error"),
        })

    classify_sum_cost = sum(r["classify_cost"] for r in runs)
    total_cost = setup_cost + classify_sum_cost

    pt_uniq = len({r["page_type"] for r in runs})
    parents = {r["parent_intent_group"] for r in runs}

    return {
        "url": url,
        "expected_page_type": expected_pt,
        "expected_parent_intent": expected_intent,
        "title": ((crawl.get("meta") or {}).get("title") or {}).get("text", "")[:120],
        "site_profile_brand": sp.get("brand"),
        "site_profile_language": sp.get("language"),
        "site_profile_location": sp.get("location"),
        "setup_cost_usd": setup_cost,
        "classify_sum_cost_usd": round(classify_sum_cost, 6),
        "total_cost_usd": round(total_cost, 6),
        "wall_s": round(time.perf_counter() - t0, 1),
        "runs": runs,
        "page_type_unique_count": pt_uniq,
        "page_type_stability": f"{4 - pt_uniq}/3",
        "parent_intent_consistency": len(parents) == 1,
        "page_type_hit_vs_expected": (
            "hit" if all(r["page_type"] == expected_pt for r in runs)
            else ("partial" if any(r["page_type"] == expected_pt for r in runs)
                  else "miss")
        ),
    }


async def main():
    grid = []
    cost_sum = 0.0
    t0 = time.perf_counter()

    dynamic = await resolve_dynamic_urls()
    if not dynamic.get("aboutyou_product") or not dynamic.get("telex_article"):
        print("Pre-flight URL resolution failed, aborting", flush=True)
        return

    targets = [
        ("aboutyou_product", dynamic["aboutyou_product"], "product_page",
         "conversion"),
        ("aboutyou_category", FIXED["aboutyou_category"], "category_page",
         "comparison_discovery"),
        ("vercel_pricing", FIXED["vercel_pricing"], "pricing_page",
         "conversion"),
        ("nextjs_docs", FIXED["nextjs_docs"], "documentation",
         "informational"),
        ("telex_article", dynamic["telex_article"], "blog_article",
         "informational"),
    ]

    for label, url, exp_pt, exp_intent in targets:
        if cost_sum > 1.80:
            print(f"\n!!! Cost ceiling approach ({cost_sum:.3f} > $1.80), halt.", flush=True)
            break
        print(f"\n=== {label} ({url}) — expected {exp_pt} / {exp_intent}", flush=True)
        result = await probe_one_url(url, exp_pt, exp_intent)
        result["label"] = label
        grid.append(result)
        cost_sum += result.get("total_cost_usd", 0.0)
        if result.get("error_setup"):
            print(f"  SETUP ERROR: {result['error_setup']}", flush=True)
            continue
        for r in result["runs"]:
            print(f"  r{r['run']}: pt={r['page_type']!r} parent={r['parent_intent_group']!r} bm={r['business_model']!r} ${r['classify_cost']:.5f}", flush=True)
        print(f"  STAB: {result['page_type_stability']}  parent-consistent: {result['parent_intent_consistency']}  hit: {result['page_type_hit_vs_expected']}  cost: ${result['total_cost_usd']:.4f}", flush=True)

    wall = round(time.perf_counter() - t0, 1)
    print(f"\n=== TOTAL: wall={wall}s  cost=${cost_sum:.4f}  audits={len(grid)} ===", flush=True)
    with open("aaa81_s2_probe.json", "w", encoding="utf-8") as f:
        json.dump({"grid": grid, "wall_s": wall, "cost_usd_total": cost_sum,
                   "dynamic_urls": dynamic}, f, indent=2, ensure_ascii=False, default=str)


if __name__ == "__main__":
    asyncio.run(main())
