"""AAA-129 Sub-step 1 (WI-1) — locked educational template layer.

FINAL, audit-independent "why this aspect matters" copy for the 7 AAA-124
aspects, in HU + EN (future-extensible: de/es). This is injected by code
(deterministic, NOT generated by Gemini — AAA-129 architectural principle:
code-level deterministic injection > prompt-only). Text is LOCKED — do not
paraphrase; bump the template_id (…_v2) if it ever changes.

Storage: raw text is held in triple-quoted blocks (soft-wrapped for source
readability) and whitespace-normalized to single-paragraph prose at import via
_norm(), so the stored value is the flowing paragraph regardless of source
line wrapping.
"""
from __future__ import annotations


def _norm(s: str) -> str:
    """Collapse source soft-wraps/indentation into single-spaced prose."""
    return " ".join(s.split())


# (template_id, HU, EN) per aspect. Text verbatim from AAA-129 S1 WI-1.
_RAW: dict[str, tuple[str, str, str]] = {
    "macro_structure": (
        "edu_macro_structure_v1",
        """A makró-struktúra az oldal egészének logikai váza — hogyan tagolódik
        szekciókra, blokkokra, és milyen sorrendben követik egymást a tartalmi
        egységek. Azért fontos, mert a keresőmotorok és az AI-asszisztensek
        (pl. Google AI Overview, ChatGPT) nem „látják" az oldalt úgy, mint egy
        ember: a szerkezetből következtetik ki, mi a fő mondanivaló és hogyan
        kapcsolódnak a részei. Egy tiszta, jól tagolt felépítés segít nekik
        megérteni és pontosan idézni az oldalt; egy átláthatatlan, egybefolyó
        szerkezet elrejti az értéket. A jó makró-struktúra tehát nem
        dizájn-kérdés — azt dönti el, hogy a gépek egyáltalán meg tudják-e
        ragadni, miről szól az oldal.""",
        """Macro structure is the logical skeleton of the whole page — how it
        breaks into sections and blocks, and in what order the content units
        follow. It matters because search engines and AI assistants (e.g.
        Google AI Overview, ChatGPT) don't "see" a page the way a person does:
        they infer the main message and how the parts relate from its
        structure. A clean, well-organized layout helps them understand and
        accurately cite the page; a tangled, undifferentiated structure hides
        its value. Good macro structure isn't a design question — it determines
        whether machines can grasp what the page is about at all.""",
    ),
    "heading_semantics": (
        "edu_heading_semantics_v1",
        """A címsor-hierarchia (H1-től H6-ig) az oldal tartalmi vázlata: a H1 a
        fő téma, a H2-H6 az alárendelt témák egyre mélyebb szintjei. Azért
        számít, mert a keresők és az AI-asszisztensek ebből a hierarchiából
        értik meg az oldal logikai felépítését — mi a fő üzenet, és mik a hozzá
        tartozó altémák. Egyetlen, egyértelmű H1 és logikusan egymásba ágyazott
        alcímsorok olyanok, mint egy jól szervezett tartalomjegyzék: a gép
        azonnal tudja, hová tartozik mi. Ha hiányoznak a címsorok vagy összevissza
        követik egymást, a gépnek találgatnia kell, miről szól az oldal — ilyenkor
        pedig könnyen rosszul vagy egyáltalán nem idézi a tartalmat.""",
        """The heading hierarchy (H1 through H6) is the page's content outline:
        the H1 is the main topic, and H2–H6 are progressively deeper levels of
        sub-topics. It matters because search engines and AI assistants read the
        page's logical structure from this hierarchy — the main message and the
        sub-topics that belong to it. A single, unambiguous H1 with logically
        nested sub-headings works like a well-organized table of contents: the
        machine immediately knows where everything belongs. When headings are
        missing or follow no clear order, the machine has to guess what the page
        is about — and then it easily cites the content wrongly, or not at all.""",
    ),
    "above_the_fold": (
        "edu_above_the_fold_v1",
        """A „hajtás feletti" rész az, ami görgetés nélkül azonnal látszik
        betöltéskor — az első képernyőnyi tartalom. Azért fontos, mert ez a
        néhány másodperc dönti el, hogy a látogató megérti-e, hová került és mit
        kínál az oldal, mielőtt továbblapozna. Egyre inkább a gépi feldolgozás is
        súlyt fektet arra, ami elöl, hangsúlyos helyen szerepel: a fő üzenetre, az
        értékajánlatra és a legfontosabb cselekvési lehetőségre. Ha a leglényegesebb
        információ csak görgetés után jelenik meg, az érték rejtve marad mind az
        ember, mind a gép számára a legfontosabb első pillanatban.""",
        """The "above the fold" area is what's immediately visible without
        scrolling when the page loads — the first screenful of content. It
        matters because these few seconds decide whether a visitor understands
        where they've landed and what the page offers before moving on.
        Increasingly, machine processing also weights what appears first and
        prominently: the main message, the value proposition, and the most
        important action. If the most essential information only appears after
        scrolling, that value stays hidden — from both people and machines — in
        the first, most important moment.""",
    ),
    "micro_semantics": (
        "edu_micro_semantics_v1",
        """A mikro-szemantika azt jelenti, hogy az oldal jelentéssel bíró
        HTML-elemekkel építi-e fel a tartalmat (pl. szövegtörzs, lista, idézet,
        kiemelés, dátum), vagy csak vizuálisan formázott, „üres" dobozokkal. Azért
        számít, mert a gép nem a betűtípusból vagy a színből érti meg egy szövegrész
        szerepét, hanem abból, milyen elemmel jelölted meg. A pontos szemantikus
        jelölés megmondja a keresőnek és az AI-nak, hogy ez itt lista, az ott idézet,
        amaz fontos kiemelés — vagyis jelentést ad a puszta megjelenés mellé. Enélkül
        a tartalom vizuálisan rendben lehet, de a gép számára megkülönböztethetetlen,
        egybemosott szöveg marad.""",
        """Micro semantics is about whether the page builds its content from
        meaningful HTML elements (e.g. body text, lists, quotes, emphasis, dates)
        or just visually styled, "empty" boxes. It matters because a machine
        doesn't understand a passage's role from its font or color — it
        understands it from which element you used to mark it up. Precise semantic
        markup tells the search engine and the AI that this is a list, that is a
        quote, this is an important emphasis — giving meaning on top of mere
        appearance. Without it, the content may look fine visually, but to a
        machine it stays indistinguishable, undifferentiated text.""",
    ),
    "inline_link_semantics": (
        "edu_inline_link_semantics_v1",
        """A szövegközi linkek szemantikája arról szól, mennyire árulkodó a
        hivatkozások szövege, és hogyan kötik össze egymással a tartalmakat. Azért
        fontos, mert a keresők és az AI-asszisztensek a linkszövegből és a linkek
        hálójából értik meg, miről szól a hivatkozott oldal és hogyan kapcsolódnak a
        témák. Egy beszédes linkszöveg (a célt pontosan leíró megfogalmazás) konkrét
        jelzést ad; a „kattints ide" típusú szöveg viszont semmit nem mond a gépnek.
        A jól felépített belső linkelés ráadásul segít a gépnek bejárni és
        összefüggésében értelmezni az egész webhelyet, nem csak az egyes oldalakat
        külön-külön.""",
        """Inline link semantics is about how telling your link text is and how
        your links connect content together. It matters because search engines
        and AI assistants understand what a linked page is about — and how topics
        relate — from the link text and the web of links. Descriptive link text
        (wording that precisely names the destination) gives a concrete signal;
        "click here"-style text tells the machine nothing. Well-built internal
        linking also helps the machine crawl and interpret the whole site in
        context, not just individual pages in isolation.""",
    ),
    "forms_conversion_points": (
        "edu_forms_conversion_points_v1",
        """A konverziós pontok azok az elemek, ahol a látogató cselekvésre váltja
        az érdeklődését — űrlapok, gombok, egyértelmű felhívások. Azért számít, mert
        ezeknek nemcsak az ember számára kell világosnak lenniük, hanem a gépi
        feldolgozás számára is: egy jól címkézett, érthető szerkezetű cselekvési pont
        egyértelművé teszi, mit kínál és mit vár az oldal. A homályos, jelöletlen vagy
        nehezen megtalálható cselekvési lehetőség elveszett szándék — a látogató
        bizonytalan lesz, a gép pedig nem ismeri fel az oldal célját. Az akadálymentes,
        egyértelmű felirat és a logikus elhelyezés teszi a konverziós pontot mind a
        felhasználó, mind a gép számára olvashatóvá.""",
        """Conversion points are the elements where a visitor turns interest into
        action — forms, buttons, clear calls to action. It matters because these
        elements need to be clear not only to people but also to machine
        processing: a well-labeled, understandably structured action point makes
        plain what the page offers and what it expects. A vague, unlabeled, or
        hard-to-find action option is lost intent — the visitor hesitates, and the
        machine can't recognize the page's purpose. Accessible, unambiguous
        labeling and logical placement are what make a conversion point readable to
        both the user and the machine.""",
    ),
    "schema_entity": (
        "edu_schema_entity_v1",
        """A strukturált adat (schema.org jelölés) és az entitás-jelzések olyan, gép
        által olvasható „címkék", amelyek kifejezetten megmondják a keresőnek és az
        AI-nak, milyen dolgok szerepelnek az oldalon — például szervezet, termék,
        személy, cikk vagy értékelés. Azért fontos, mert nem hagyja találgatásra a
        gépet: explicit, félreérthetetlen jelzést ad a tartalom jelentéséről. Ennek
        köszönhetően jelenhetnek meg a gazdagabb keresőtalálatok, és ez segíti az
        AI-asszisztenseket abban, hogy pontosan és helyesen idézzék az oldalt.
        Strukturált adat nélkül a gép kizárólag a nyers szövegből próbálja
        kikövetkeztetni ugyanezt — bizonytalanabbul és nagyobb hibalehetőséggel.""",
        """Structured data (schema.org markup) and entity signals are
        machine-readable "labels" that explicitly tell the search engine and the
        AI what things appear on the page — for example an organization, product,
        person, article, or review. It matters because it leaves nothing to the
        machine's guesswork: it gives an explicit, unambiguous signal about the
        meaning of the content. This is what enables richer search results, and it
        helps AI assistants cite the page precisely and correctly. Without
        structured data, the machine has to infer all of this from the raw text
        alone — less reliably and with more room for error.""",
    ),
}

# Final locked store: aspect -> {template_id, text:{hu,en}}.
EDU_TEMPLATES: dict[str, dict] = {
    aspect: {
        "template_id": tid,
        "text": {"hu": _norm(hu), "en": _norm(en)},
    }
    for aspect, (tid, hu, en) in _RAW.items()
}
